apiVersion: apps/v1
kind: Deployment
metadata:
  name: housing
spec:
  replicas : 1
  selector:
    matchLabels:
      app: housing
  template:
    metadata:
      labels:
        app: housing
    spec:
      containers:
      - name: housing
        image: arpitppatel/housing-kn:v1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "512Mi"
            cpu: "200m"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: housing
spec:
  selector:
    app: housing
  ports:
  - port: 1234
    targetPort: 8000
